# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 03:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBorrowTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=8)),
                ('tel', models.CharField(max_length=14)),
                ('given_date', models.DateField(auto_now_add=True)),
                ('ret_date', models.DateField()),
                ('items', django.contrib.postgres.fields.jsonb.JSONField()),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
