# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_modemimeinumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentborrowtransactions',
            name='items',
        ),
        migrations.AddField(
            model_name='equipmentborrowtransactions',
            name='item',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentborrowtransactions',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
