# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-14 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_equipmentborrowtransactions_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentborrowtransactions',
            name='returned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentborrowtransactions_returned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentborrowtransactions',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipmentborrowtransactions_given_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
