# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-14 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180714_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='library',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
