# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('maxBookings', models.IntegerField(default=10)),
            ],
        ),
    ]
