# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180827_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdayschedule',
            name='maxBookingsReached',
            field=models.BooleanField(default=False),
        ),
    ]
