# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_weekdayschedule_maxbookingsreached'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numberOfBookings', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.WeekDaySchedule')),
            ],
        ),
    ]
