# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookeddates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdayschedule',
            name='weekDay',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10),
        ),
    ]
