# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
