# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20180827_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentbookings',
            old_name='Matricule',
            new_name='matricule',
        ),
    ]
