# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20180827_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbookings',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentbookings',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
