# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20180827_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffbookings',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='studentbookings',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='staffbookings',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentbookings',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Students'),
            preserve_default=False,
        ),
    ]
