# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20180829_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='matricule',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
