# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20180829_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbookings',
            name='matricule',
        ),
        migrations.AlterField(
            model_name='staffbookings',
            name='reason',
            field=models.CharField(choices=[('WORK', 'work'), ('CLASS', 'class')], max_length=8),
        ),
    ]
